### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by Vaccano** [kisssdev/aurelia-kis-oidc#7]
Your documentation is excellent.  I am sure that if I had a regular javascript application it would work.

But it is proving hard to get running when using typescript.

Adding typescript definition files would really help out!  (Mostly for OpenidRouting and Oauth2Interceptor)

**Comment by kisssdev** [comment]
I have added the ts types. You may give a try. I will also create a ts sample soon.

**Comment by kisssdev** [comment]
The sample is here: https://github.com/kisssdev/aurelia-kis-oidc-sample
